import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @serwist/next on every build, gitignored, and minified —
    // linting it produced 86 of 110 problems and drowned the real ones.
    "public/sw.js",
    "public/sw.js.map",
    "public/swe-worker-*.js",
    // The Supabase CLI writes generated, minified JS into supabase/.temp on
    // every `supabase start`. Gitignored, but ESLint does not read
    // .gitignore, so without this the commit gate lints the local stack's
    // own runtime and fails on `var`.
    "supabase/**",
  ]),
  {
    rules: {
      // Advisory here, not a gate. Two legitimate patterns in this codebase
      // trip it and the rule's suggested fix is wrong for both:
      //   1. Reading localStorage / userAgent after mount (collapsible-section,
      //      fold-section, install-hint). Reading them during render is a
      //      hydration mismatch under SSR, so the effect is the correct place.
      //   2. Resetting a dialog's form when it opens. A real smell — React
      //      prefers a `key` reset — but working, and the identity bug that
      //      made it dangerous (a fresh `initial` object each render) is fixed.
      // Kept visible as a warning so new instances are still noticed; the
      // commit gate blocks on errors only.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
]);

export default eslintConfig;
